### ISSUE TITLE
[security] API Explorer issues insecure tokens.

### ISSUE THREAD

**Issue by jaredhanson** [auth0/api-explorer#108]
API Explorer currently issues tokens as follows:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkdlVjeUNOeGE5eXdJSUNHM0ptY05pV2NENWJWUE5pbiIsInNjb3BlcyI6eyJjbGllbnRfZ3JhbnRzIjp7ImFjdGlvbnMiOlsicmVhZCIsImNyZWF0ZSJdfX0sImlhdCI6MTQ1ODU3NDkwMiwianRpIjoiY2U5OGRhZjUxYzVhNjAxMWU2NzQyYzJkZGUxMDZlMzUifQ.vXKyGIEVmrNrAgvhT8s43Q0NOZOWLYMg7dgdCOVt2_Y
```

```
{
  "alg": "HS256",
  "typ": "JWT"
}
.
{
  "aud": "dvUcyCNxa9ywIICG3JmcNiWcD5bVPNin",
  "scopes": {
    "client_grants": {
      "actions": [
        "read",
        "create"
      ]
    }
  },
  "iat": 1458574902,
  "jti": "ce98daf51c5a6011e6742c2dde106e35"
}
```

Such tokens are accepted by APIv2, for backwards compatibility reasons, but they are insecure.  The insecurity results from APIv2 not being identified in the `aud` claim.

The token format should be changed to look as follows:

```
{
  "alg": "RS256",
  "typ": "JWT"
}
.
{
  "aud": "https://{tenant}.auth0.com/api/v2/",
  "scope": "read:client_grants create:client_grants",
  "iat": 1458574902,
  "jti": "ce98daf51c5a6011e6742c2dde106e35",
  "sub": "usr_123"
  "exp": 1458574904
}
```

The relevant differences are:

1. `aud` changes to `https://{tenant}.auth0.com/api/v2/`.  Note that {tenant} must be replaced with an actual tenant name.
2. `scopes` is renamed to `scope` and is a space-separated string with a list of scope values.
3. `sub` is added, and contains the user ID of the logged-in user.
4. `exp` claim is added and should be releatively short, no more than 7 days after the issued time.
6. The token should be signed with the tenant-level signing key, ie the signing key associated with the "global" client.

**Comment by woloski** [comment]
oh yeah I saw this conversation. Ok we should prioritize this then @astanciu
